spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/isadb?currentSchema=isa
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
server:
  port : 8089
