spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  datasource:
    url: jdbc:postgresql://localhost:5432/isadb?currentSchema=isaadb
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
#    hikari:
#      schema: isaadb
      
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: sokolicc.dji.acc@gmail.com
    password: dmpcnamghlyqqpto
    port: '587'
    
    
server:
  port : 8089
 
